version: '3.4'

volumes:
  dbdata:
    name: pgdata

  redisdata:
    name: redisdata

services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    volumes:
      - "redisdata:/data"
    restart: always

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
       - ${DB_PORT}:${DB_PORT}
    volumes:
      - 'dbdata:/var/lib/mysql'
    restart: always


  server:
    tty: true
    container_name: server
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "./docker-entrypoint.sh"
    env_file: .env
    volumes:
      - .:/code
    links:
      - "db:database"
      - "redis:redis"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - redis
    restart: always

